package io.bundler

/**
 * Simple interface for the injector.
 * A class that implements this interface will be generated by the processor.
 */
interface Injector<T : Any> {

    fun inject(target: T)
}
